# .github/.github/workflows/discord-pr-notifier.yml

name: 'Discord PR Notifier'

# Gatilho: executa a action quando um novo Pull Request é aberto
on:
  pull_request:
    types: [opened]

jobs:
  notify_discord:
    name: 'Send PR Notification to Discord'
    runs-on: ubuntu-latest
    steps:
      - name: 'Send notification'
        run: |
          # Monta a mensagem em formato JSON para o Discord Embed
          JSON_PAYLOAD=$(printf '{
            "content": "🎉 **Novo Pull Request!** 🎉",
            "embeds": [{
              "title": "%s",
              "url": "%s",
              "description": "**Repositório:** %s\n**Autor:** %s",
              "color": 3447003,
              "author": {
                "name": "%s",
                "icon_url": "%s"
              },
              "footer": {
                "text": "Notificação de PR"
              }
            }]
          }' \
          "${{ github.event.pull_request.title }}" \
          "${{ github.event.pull_request.html_url }}" \
          "${{ github.event.repository.full_name }}" \
          "${{ github.event.pull_request.user.login }}" \
          "${{ github.event.pull_request.user.login }}" \
          "${{ github.event.pull_request.user.avatar_url }}")
          
          # Envia a notificação usando cURL para o Webhook do Discord
          curl -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD" \
               "https://discord.com/api/webhooks/1394398569611661352/OPHZnFP5Q-1_0R0QI94BsBqw0j3eMqqB06AmUasuZ9_XAhamadmcxwWKRB9fpvbOEV9Q"